config/routes.rb
Ether::Application.routes.draw do
  resources :replies, :only => [:create, :destroy, :show]

  get "/groups/:group_id/new", :to => "posts#new", :as => "new_post"
  resources :posts, :except => :new

  get "/groups/:group_id/quit", :to => "groups#quit", :as => "quit_group"
  get "/groups/:group_id/join", :to => "groups#join", :as => "join_group"
  resources :groups

  get "/users/:login_name", :to => "users#show", :as => "user_profile"
  devise_for :users, :path => "", :path_names => { :sign_in => 'signin', :sign_out => 'signout', :sign_up => 'signup' }
  get "/dashboard", :to => "home#dashboard"

  root :to => "home#index"

end

app/models/Membership.rb
class Membership < ActiveRecord::Base
  belongs_to :user
  belongs_to :group

  validates_uniqueness_of :user_id, :scope => :group_id
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.admin?
      can :manage, :all
    elsif user.confirmed?
      can :create, Post, :group_id => user.group_ids
      can :update, Post, :user_id => user.id
      can :join, Group do |group|
        !group.users.include? user
      end
      can :read, [Group, Post, User]
      can :create, Reply
    else
      can :read, :all
      cannot [:create, :update], Group
    end
  end
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :posts
  has_many :memberships
  has_many :users, :through => :memberships
  has_attached_file :icon,
  :default_url => "/images/group_icons/default/:style.:extension",
  :path => ":rails_root/public/images/group_icons/:id/:style.:extension",
  :url => "/images/group_icons/:id/:style.:extension", :styles => {
    :large => ["114x114>", :png],
    :normal => ["88x88>", :png],
    :small  => ["68x68>", :png]
  }

  validates_presence_of :name
  validates_uniqueness_of :name
  validates_length_of :name, :maximum => 16
  validates_length_of :description, :maximum => 128
  validates_attachment_size :icon, :less_than => 640.kilobytes
  validates_attachment_content_type :icon, :content_type => [
    "image/jpeg", "image/png", "image/gif"
  ]
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
  has_many :replies

  validates_presence_of :title
  validates_presence_of :content
  validates_length_of :title, maximum:64

  paginates_per 16
end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates_presence_of :content
  
  after_create :bump_post

  private

  def bump_post
    self.post.last_replied = self.created_at
    self.post.save
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :full_name, :login_name

  has_many :posts
  has_many :memberships
  has_many :groups, :through => :memberships
  has_many :replies
  has_attached_file :avatar,
  :default_url => "/images/user_avatars/default/:style.:extension",
  :path => ":rails_root/public/images/user_avatars/:id/:style.:extension",
  :url => "/images/user_avatars/:id/:style.:extension", :styles => {
    :large => ["114x114>", :png],
    :normal => ["88x88>", :png],
    :small  => ["68x68>", :png]
  }

  validates_presence_of :login_name
  validates_length_of :login_name, :within => 4..16
  validates_uniqueness_of :login_name
  validates_attachment_size :avatar, :less_than => 640.kilobytes
  validates_attachment_content_type :avatar, :content_type => [
    "image/jpeg", "image/png", "image/gif"
  ]

  def member?(group)
    group.user_ids.include?(self.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :store_group_id

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end

  private

  def store_group_id
    session[:group_id] = params[:group_id] if params[:group_id]
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  load_and_authorize_resource

  def index
  end

  def new
  end

  def show
    @group.description = Redcarpet.new(@group.description, :smart, :filter_html).to_html.html_safe
    @posts = @group.posts.order("last_replied DESC").page(params[:page])
  end

  def edit
  end

  def create
    respond_to do |format|
      if @group.save
        format.html{redirect_to(@group)}
      else
        format.html{render :action => 'new'}
      end
    end
  end

  def update
    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html{redirect_to(@group)}
      else
        format.html{render :action => 'edit'}
      end
    end
  end

  def join
    @group = Group.find(params[:group_id])
    @group.users << current_user
    redirect_to @group, :notice => "You have joined this group."
  end

  def quit
    @group = Group.find(params[:group_id])
    @group.users.delete(current_user)
    redirect_to @group, :notice => "You have quit this group."
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @groups = Group.all
  end

  def dashboard
    redirect_to root_url, :alert => "Please login to access dashboard!" unless current_user
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :load_group_post, :only => [:new, :create]
  before_filter :store_post_id
  load_and_authorize_resource

  def new
  end

  def create
    @post.update_attributes(params[:post])

    respond_to do |format|
      if @post.save
        format.html{redirect_to(@post)}
      else
        format.html{render :action => 'new'} 
      end
    end
  end

  def show
    @reply = Reply.new
  end

  def edit
  end

  def update
    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html{redirect_to(@post)}
      else
        format.html{render :action => 'edit'}
      end
    end
  end

  private

  def store_post_id
    session[:post_id] = params[:id] if params[:id]
  end

  def load_group_post
    @post = Group.find(session[:group_id]).posts.build(:user_id => current_user.id)
  end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  before_filter :load_post_reply, :only => :create
  load_and_authorize_resource

  def create
    @post = @reply.post
    @reply.update_attributes(params[:reply])

    respond_to do |format|
      if @reply.save
        format.html{redirect_to(@post)}
      else
        format.html{render :controller => :post, :action => 'show'} 
      end
    end
  end

  def destroy
    @reply.destroy
    redirect_to post_path(session[:post_id])
  end

  private

  def load_post_reply
    @reply = Post.find(session[:post_id]).replies.build(:user_id => current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.where(:login_name => params[:login_name]).first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title)
    content_for(:title){ page_title }
  end

  def name(page_name)
    content_for(:name){ page_name }
  end

  def htmlize(content)
    Redcarpet.new(content, :smart, :filter_html).to_html.html_safe
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def group_id
    @post.group_id ? @post.group_id : @post.group_id = session[:group_id]
  end
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_form.html.erb
<%= form_for @group, :html => {:multipart => true, :class => "form"} do |f| %>
  <% if @group.errors.any? %>
    <h2><%= pluralize(@group.errors.count, 'error') %> stop this group being saved:</h2>
    <% @group.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  <% end %>
  <p><%= f.label :name %>
  <%= f.text_field :name %></p>
  <p><%= f.label :description %>
  <%= f.text_area :description %></p>
  <p><%= f.label :icon %>
  <%= f.file_field :icon %></p>
  <p><%= f.submit 'save' %></p>
<% end %>

app/views/groups/edit.html.erb
<% title "Groups - #{@group.name} - Update group info" %>
<% name "Groups > #{@group.name} > Update group info" %>
<%= content_for :action do%>
<%= link_to 'Cancel', group_path(@group.id) %>
<% end %>
<%= render 'form' %>

app/views/groups/new.html.erb
<% title "Groups - New group" %>
<% name "Groups > New group" %>
<% content_for :action do%>
<%= link_to 'Cancel', root_path %>
<% end %>
<%= render 'form' %>

app/views/groups/show.html.erb
<% title "Groups - #{@group.name}" %>
<% name "Groups > #{@group.name}" %>
<%= content_for :action do%>
<% if current_user.try(:admin?) %>
<%= link_to 'Edit', edit_group_path(@group) %>
<% end %>
<% if user_signed_in? && !current_user.try(:member?, @group) %>
<%= link_to 'Join', join_group_path(@group) %>
<% elsif current_user.try(:member?, @group) %>
<%= link_to 'Quit', quit_group_path(@group) %>
<%= link_to 'New', new_post_path(@group) %>
<% end %>
<% end %>
<section id="group">
  <%= image_tag @group.icon.url(:small), :class => :icon %>
  <article>
    <header>
      <p> Created on <time datetime="<%= @group.created_at.localtime.iso8601 %>"><%= @group.created_at.localtime.strftime("%m/%d/%Y") %></time></p>
    </header>
    <section class="text"><%= @group.description.gsub(/<\/?.*?>/, "").insert(0, "<p>").insert(-1, "</p>") %></section>
  </article>
</section>
<ul id="posts">
  <% @posts.each do |post| %>
  <li>
    <%= image_tag post.user.avatar.url(:small), :class => :avatar %>
    <article>
      <header>
        <h1><%= link_to post.title, post_path(post) %></h1>
        <p>Posted by 
          <%= link_to post.user.login_name, user_profile_path(post.user.login_name) %>
          <time datetime="<%= post.created_at.localtime.iso8601 %>"> <%= time_ago_in_words(post.created_at.localtime) %> ago</time>
          <% if post.replies.exists? %>
          | Last Replied by <%= link_to post.replies.last.user.login_name, user_profile_path(post.replies.last.user.login_name) %>
          <time datetime="<%= post.last_replied.localtime.iso8601 %>"> <%= time_ago_in_words(post.last_replied.localtime) %> ago</time>
          <% end %>
        </p>
        <%= link_to pluralize(post.replies.count, "Reply"), post_path(post) + "#replies", :class => "replies" %>
      </header>
      <section class="text"><%= htmlize(post.content) %></section>
    </article>
  </li>
  <% end %>
</ul>
<%= paginate @posts %>

app/views/home/dashboard.html.erb
<% title "Dashboard" %>
<h1><%= yield(:title) %></h1>
<p><%= current_user.login_name %></p>

app/views/home/index.html.erb
<% title "Where we get connected" %>
<% name "Home" %>
<%= content_for :action do %>
<% if current_user.try(:admin)%>
<%= link_to 'New', new_group_path %>
<% end %>
<% end %>
<section id="groups">
<% @groups.each do |group| %>
  <a class="group" href= "<%= url_for group %>" title="<%= group.name %>">
    <%= image_tag group.icon.url(:small) %>
    <span><%= group.name.truncate(12) %></span>
  </a>
<% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>Ether - <%= yield(:title) %></title>
<link rel="stylesheet" media="all" href="/styles/lessv4.css"/>
<link rel="stylesheet" media="all" href="/styles/main.css"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<script src="/scripts/head.min.js"></script>
<script>
  head.js(
    {jquery:"https://ajax.googleapis.com/ajax/libs/jquery/1.5.0/jquery.min.js"},
    "/scripts/less-grid-4.js"
  );
</script>
<%= csrf_meta_tag %>
</head>
<body>
<header id="top">
  <nav>
    <ul>
      <li><a href="/">Home</a></li>
      <li><a href="/dashboard">Dashboard</a></li>
    </ul>
  </nav>
  <hgroup>
    <h1>Project Ether</h1>
    <h2>Where we get connected</h2>
  </hgroup>
</header>
<% if notice %>
<p><%= notice %></p>
<% end %>
<% if alert %>
<p><%= alert %></p>
<% end %>

<section id="content">
  <h1 id="guide">Ether &gt; <%= yield(:name) %>
    <span id="actions"><%= render "shared/session_actions" %><%= content_for(:action) %></span>
  </h1>
  <%= yield %>
</section>

<footer id="bottom">
  <h1>© 2011 Grandline, All rights reserved.</h1>
</footer>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, :html => {:class => "form"} do |f| %>
  <% if @post.errors.any? %>
    <h2><%= pluralize(@post.errors.count, 'error') %> stop this post being saved:</h2>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  <% end %>
  <p><%= f.label :title %>
  <%= f.text_field :title %></p>
  <p><%= f.label :content %>
  <%= f.text_area :content %></p>
  <%= f.hidden_field :group_id, :value => group_id %>
  <p id="submit"><%= f.submit 'Save' %></p>
<% end %>

app/views/posts/edit.html.erb
<% title "Groups - #{@post.group.name} - New Post" %>
<% name "Groups > #{@post.group.name} > New Post" %>
<% content_for :action do%>
<%= link_to 'Cancel', post_path(@post) %>
<% end %>
<%= render 'form' %>

app/views/posts/new.html.erb
<% title "Groups - #{@post.group.name} - New Post" %>
<% name "Groups > #{@post.group.name} > New Post" %>
<% content_for :action do%>
<%= link_to 'Cancel', group_path(group_id) %>
<% end %>
<%= render 'form' %>

app/views/posts/show.html.erb
<% title "Groups - #{@post.group.name} - #{@post.title}" %>
<% name "Groups > #{@post.group.name} > #{@post.title}" %>
<% content_for :action do%>
<% if current_user.try(:admin?) || @post.user == current_user %>
<%= link_to "Edit", edit_post_path(@post) %>
<% end %>
<%= link_to "Back to group", group_path(@post.group) %>
<% end %>
<section id="post">
  <%= image_tag @post.user.avatar.url(:small), :class => :avatar %>
  <article>
    <header>
      <p>Posted by  <%= link_to @post.user.login_name, user_profile_path(@post.user.login_name) %>
        <time datetime="<%= @post.created_at.localtime.iso8601 %>"> <%= time_ago_in_words(@post.created_at.localtime) %> ago</time>
      </p>
    </header>
    <section class="text"><%= htmlize(@post.content) %></section>
  </article>
</section>

<ul id="replies">
  <% @post.replies.each do |reply| %>
  <li id="reply-<%= reply.id %>">
    <%= image_tag reply.user.avatar.url(:small), :class => :avatar %>
    <article>
      <header>
        <p><%= link_to reply.user.login_name, user_profile_path(reply.user.login_name) %> replied 
          <time datetime="<%= reply.created_at.localtime.iso8601 %>"> <%= time_ago_in_words(reply.created_at.localtime) %> ago</time>
        </p>
        <% if current_user.try(:admin) || current_user == reply.user  %>
        <%= button_to "Destroy", reply, :method => :delete, :class => "delet_reply" %>
        <% end %>
      </header>
      <section class="text"><%= htmlize(reply.content) %></section>
    </article>
  </li>
  <% end %>
</ul>

<% if user_signed_in? %>
<%= form_for @reply, :html => {:class => "form"} do |f| %>
  <% if @reply.errors.any? %>
    <h2><%= pluralize(@reply.errors.count, 'error') %> stop this reply being saved:</h2>
    <% @reply.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  <% end %>
  <p>Leave your reply here</p>
  <p><%= f.label :content %>
  <%= f.text_area :content, :rows => 8 %></p>
  <p id="submit"><%= f.submit 'Save' %></p>
<% end %>
<% end %>

app/views/shared/_session_actions.html.erb
<% if user_signed_in? %>
<%= link_to "Sign out", destroy_user_session_path %>
<% elsif controller_name != 'sessions' %>
<%= link_to "Sign in", new_user_session_path %>
<% end %>
<% if !user_signed_in? && controller_name != 'registrations' %>
<%= link_to "Sign up", new_user_registration_path %>
<% end %>

app/views/users/show.html.erb
<% if @user %>
<h1><%= @user.login_name %></h1>
<% else %>
<h1>Non existing user.</h1>
<% end %>